CREATE DATABASE PapelesCorrugados;

USE PapelesCorrugados;

CREATE TABLE Compania(idCompania VARCHAR(4) NOT NULL,
		     nombre VARCHAR(70) NOT NULL,
		     estatus BOOLEAN NULL,
             PRIMARY KEY(idCompania)) ENGINE = InnoDB;

CREATE TABLE Rol(idCompania VARCHAR(4) NOT NULL,
		 	 rol VARCHAR(4) NOT NULL,
		 	 estatus BOOLEAN NULL,
		 	 PRIMARY KEY(rol),
		 	 FOREIGN KEY(idCompania) REFERENCES Compania(idCompania)) ENGINE = InnoDB;

CREATE TABLE Usuario(idUsuario VARCHAR(20) NOT NULL,
		     idCompania VARCHAR(4) NOT NULL,
		     nombre VARCHAR(50) NOT NULL,
             contrasena VARCHAR(255) NOT NULL,
             rol VARCHAR(4) NULL,
		     estatus BOOLEAN NULL,
             PRIMARY KEY(idUsuario),
		     FOREIGN KEY(idCompania) REFERENCES Compania(idCompania),
		     FOREIGN KEY(rol) REFERENCES Rol(rol)) ENGINE = InnoDB;

CREATE TABLE Permiso(idUsuario  VARCHAR(20)  NOT NULL,
		     permiso    VARCHAR(20)  NOT NULL,
		     estatus    BOOLEAN          NULL,
		     FOREIGN KEY(idUsuario) REFERENCES Usuario(idUsuario)) ENGINE = InnoDB;

CREATE TABLE Agente(idCompania VARCHAR(4) NOT NULL,
		     idRepresentante VARCHAR(10) NOT NULL,
		     nomRepresentante VARCHAR(30) NOT NULL,
		     estatus BOOLEAN NULL,
             PRIMARY KEY(idRepresentante),
             FOREIGN KEY(idCompania) REFERENCES Compania(idCompania)) ENGINE = InnoDB;

CREATE TABLE Almacen(idAlmacen VARCHAR(10) NOT NULL,
		     idCompania VARCHAR(4) NOT NULL,
		     descripcion VARCHAR(30) NOT NULL,
		     estatus  BOOLEAN NULL,
             PRIMARY KEY(idAlmacen),
             FOREIGN KEY(idCompania) REFERENCES Compania(idCompania)) ENGINE = InnoDB;

CREATE TABLE Cliente(idCliente VARCHAR(10)	NOT NULL,
	         		 idCompania VARCHAR(4)	NOT NULL,
                     idRepresentante VARCHAR(10) NOT NULL,
                     idLista VARCHAR(10) NOT NULL,
                     idAlmacen VARCHAR(10) NOT NULL,
                     nombreCliente VARCHAR(100) NOT NULL,
                     estatusCliente INT NOT NULL,
                     analista VARCHAR(10) NOT NULL,
                     divisa VARCHAR(3) NOT NULL,
                     limCredito BIGINT(10) NOT NULL,
                     saldoOrden DOUBLE(15,2)	NOT NULL,
                     saldoFactura DOUBLE(15,2)	NOT NULL,
                     bloqueo BOOLEAN NOT NULL,
		     		 estatus BOOLEAN NULL,
                     PRIMARY KEY(idCliente),
                     FOREIGN KEY(idCompania) REFERENCES Compania(idCompania),
                     FOREIGN KEY(idRepresentante) REFERENCES Agente(idRepresentante),
                     FOREIGN KEY(idAlmacen) REFERENCES Almacen(idAlmacen)) ENGINE = InnoDB;

CREATE TABLE ArticuloExistente(idArticulo VARCHAR(20)NOT NULL,
          		       		 idCompania VARCHAR(4) NOT NULL,
                        	 descripcion VARCHAR(70) NOT NULL,
                             costoEstandar DOUBLE(15,4) NOT NULL,
			       			 estatus BOOLEAN NULL,
                             PRIMARY KEY(idArticulo),
                             FOREIGN KEY(idCompania) REFERENCES Compania(idCompania)) ENGINE = InnoDB;

CREATE TABLE ArticuloVendido(folio INT NOT NULL,
				 idCompania VARCHAR(4) NOT NULL,
			     idArticulo VARCHAR(20) NOT NULL,
			     idAlmacen VARCHAR(4) NOT NULL,
                 idCliente VARCHAR(10) NOT NULL,
                 newRep VARCHAR(12)	NOT NULL,
			     udVta VARCHAR(4) NOT NULL,
			     stock DOUBLE(15,2)	NOT NULL,
                 codAviso VARCHAR(3) NOT NULL,
			     estatus BOOLEAN NULL,
		         PRIMARY KEY(folio),
                 FOREIGN KEY(idArticulo) REFERENCES ArticuloExistente(idArticulo),
                 FOREIGN KEY(idCliente)  REFERENCES Cliente(idCliente),
			     FOREIGN KEY(idCompania) REFERENCES Compania(idCompania)) ENGINE = InnoDB;

CREATE TABLE Inventario(idCompania VARCHAR(4) NOT NULL,
				 idAlmacen VARCHAR(4) NOT NULL,
				 idArticulo VARCHAR(20) NOT NULL,
				 stock DOUBLE(15,2)	NOT NULL,
				 estatus BOOLEAN NULL,
				 FOREIGN KEY(idCompania) REFERENCES Compania(idCompania),
                 FOREIGN KEY(idAlmacen) REFERENCES Almacen(idAlmacen),
             	 FOREIGN KEY(idArticulo) REFERENCES ArticuloExistente(idArticulo)) ENGINE = InnoDB; 

CREATE TABLE ListaPrecio(idCompania VARCHAR(4) NOT NULL,
			 	 idLista VARCHAR(10) NOT NULL,
			 	 idArticulo VARCHAR(20) NOT NULL,
			 	 nivelDscto INT NOT NULL,
			 	 cantOlmp BIGINT(10) NOT NULL,
			 	 precio DOUBLE(15,2) NOT NULL,
			 	 descuento FLOAT(15,2) NOT NULL,
			 	 impDesc DOUBLE(15,2) NOT NULL,
			 	 fechaCaducidad VARCHAR(10)	NOT NULL,
			 	 fechaInicio VARCHAR(10) NOT NULL,
			 	 estatus BOOLEAN NULL,
			 	 FOREIGN KEY(idCompania) REFERENCES Compania(idCompania),
			 	 FOREIGN KEY(idArticulo) REFERENCES ArticuloExistente(idArticulo)) ENGINE = InnoDB;

CREATE TABLE DirEnt(idCompania VARCHAR(4) NOT NULL,
		    	 idCliente VARCHAR(10) NOT NULL,
		    	 nombreEntrega VARCHAR(50) NOT NULL,
		    	 dirEnt VARCHAR(10) NOT NULL,
		    	 direccion VARCHAR(100) NOT NULL,
		    	 codPost VARCHAR(5) NOT NULL,
	   	    	 municipio VARCHAR(30) NOT NULL,
		    	 estado VARCHAR(30) NOT NULL,
		    	 pais VARCHAR(3) NOT NULL,
		    	 codRuta VARCHAR(5) NOT NULL,
		    	 rfc VARCHAR(20) NOT NULL,
		    	 telefono VARCHAR(20) NOT NULL,
		    	 observaciones VARCHAR(100) NOT NULL,
		    	 estatus BOOLEAN NULL,
		    	 FOREIGN KEY(idCompania) REFERENCES Compania(idCompania),
		    	 FOREIGN KEY(idCliente) REFERENCES Cliente(idCliente)) ENGINE = InnoDB;

CREATE TABLE Orden(idOrden BIGINT(10) NOT NULL,
		   		 idCompania VARCHAR(4) NOT NULL,
		   		 idCliente VARCHAR(10) NOT NULL,
				 ordenCompra BIGINT(10) NOT NULL,
				 fechaOrden VARCHAR(10) NOT NULL,
				 dirEnt VARCHAR(10) NOT NULL,
				 estatusOrden INT NOT NULL,
				 tFac DATETIME NULL,
				 tCXC DATETIME NULL,
				 tPRE DATETIME NULL,
				 tCST DATETIME NULL,
				 tING DATETIME NULL,
				 tPLN DATETIME NULL,
				 tFEC DATETIME NULL,
				 total FLOAT(15,2) NULL,
				 vFac BOOLEAN NULL,
				 vCXC BOOLEAN NULL,
				 vPRE BOOLEAN NULL,
				 vCST BOOLEAN NULL,
				 vING BOOLEAN NULL,
				 vPLN BOOLEAN NULL,
				 vFEC BOOLEAN NULL,	
				 estatus BOOLEAN NULL,
				 PRIMARY KEY(idOrden),
				 FOREIGN KEY(idCompania) REFERENCES Compania(idCompania),
				 FOREIGN KEY(idCliente) REFERENCES Cliente(idCliente)) ENGINE = InnoDB;

CREATE TABLE Factura(numFact 	  BIGINT(10)	NOT NULL,
		     	 idCompania VARCHAR(4) NOT NULL,
		     	 idOrden BIGINT(10) NOT NULL,
		     	 idArticulo VARCHAR(20) NOT NULL,
		     	 idCliente VARCHAR(10) NOT NULL,
		     	 folio INT NOT NULL,
	 	     	 fechaFac VARCHAR(10) NOT NULL,
		     	 entrega INT NOT NULL,
		     	 tipoTrans VARCHAR(4) NOT NULL,
		     	 estatus BOOLEAN NULL,
		     	 PRIMARY KEY(numFact),
		     	 FOREIGN KEY(idCompania) REFERENCES Compania(idCompania),
		     	 FOREIGN KEY(idOrden) REFERENCES Orden(idOrden),
		     	 FOREIGN KEY(idArticulo) REFERENCES ArticuloExistente(idArticulo),
		     	 FOREIGN KEY(folio) REFERENCES ArticuloVendido(folio),
		     	 FOREIGN KEY(idCliente) REFERENCES Cliente(idCliente)) ENGINE = InnoDB;

CREATE TABLE CantEntregada(idCompania VARCHAR(4) NOT NULL,
				 idOrden BIGINT(10) NOT NULL,
				 folio INT NOT NULL,
				 idArticulo VARCHAR(20) NOT NULL,
				 fechaMov VARCHAR(10) NOT NULL,
				 hora BIGINT(10) NOT NULL,
				 cantidad DOUBLE(15,2) NOT NULL,
				 secuencia INT NOT NULL,
				 posicion INT NOT NULL,
				 tipoReg INT NOT NULL,
				 estatus BOOLEAN NULL,
				 FOREIGN KEY(idCompania) REFERENCES Compania(idCompania),
				 FOREIGN KEY(idArticulo) REFERENCES ArticuloExistente(idArticulo),
				 FOREIGN KEY(idOrden) REFERENCES Orden(idOrden),
				 FOREIGN KEY(folio) REFERENCES ArticuloVendido(folio)) ENGINE = InnoDB;

CREATE TABLE ReporteOrden(idOrden BIGINT(10) NOT NULL,
			  	 idCompania VARCHAR(4) NOT NULL,
			  	 folio INT NOT NULL,
			  	 numFact BIGINT(10) NOT NULL,
			  	 ordenBaan BIGINT(10) NOT NULL,
			  	 idCliente VARCHAR(10) NOT NULL,
			  	 nombreCliente VARCHAR(100) NOT NULL,
			  	 dirEnt VARCHAR(10) NOT NULL,
			  	 idArticulo VARCHAR(20) NOT NULL,
			  	 ordenCompra BIGINT(10) NOT NULL,
			  	 cantidad DOUBLE(15,2) NOT NULL,
			  	 precio  DOUBLE(15,2) NOT NULL,
			  	 descripcion VARCHAR(70) NOT NULL,
			  	 fechaOrden VARCHAR(10) NOT NULL,
			  	 fechaSolicitud VARCHAR(10) NOT NULL,
			  	 fechaEntrega VARCHAR(10) NOT NULL,
			  	 vFac BOOLEAN NULL,
		   	  	 vCXC BOOLEAN NULL,
		   	  	 vPRE BOOLEAN NULL,
		   	  	 vCST BOOLEAN NULL,
		   	  	 vING BOOLEAN NULL,
		   	  	 vPLN BOOLEAN NULL,
		   	  	 vFEC BOOLEAN NULL,
			  	 producido INT NOT NULL,
			  	 entregado INT NOT NULL,
			  	 acumulado INT NOT NULL,
			  	 total FLOAT(15,2) NOT NULL,
			  	 costo FLOAT(15,2) NOT NULL,
			  	 moneda VARCHAR(3) NOT NULL,
			  	 nota VARCHAR(70) NOT NULL,
			  	 estatus BOOLEAN NULL,
			  	 FOREIGN KEY(idOrden) REFERENCES Orden(idOrden),
			  	 FOREIGN KEY(idCompania) REFERENCES Compania(idCompania),
			  	 FOREIGN KEY(idArticulo) REFERENCES ArticuloExistente(idArticulo),
			  	 FOREIGN KEY(idCliente) REFERENCES Cliente(idCliente)) ENGINE = InnoDB;

CREATE TABLE Registro_bajas(idUsuario VARCHAR(20) NOT NULL,
							fechaBaja VARCHAR(10) NOT NULL,
							descripcionBajas VARCHAR(30) NOT NULL,
							FOREIGN KEY(idUsuario) REFERENCES Usuario(idUsuario)) ENGINE = InnoDB;